universe        = docker
docker_image    = python:3.11-bookworm
stream_input    = true

# Set the project directory as the initial directory
initialdir      = /home/make00009/safe-llm-finetune

# send the whole folder into the container
transfer_input_files = pipeline/

# no need to prefix with folder name, because the container runs from that context
executable      = lora_submit/run.sh
arguments       =

# Resources
request_gpus    = 1
request_cpus    = 2
request_memory  = 32 GB

# Required by SIC infrastructure
requirements    = UidDomain == "cs.uni-saarland.de" && (TARGET.CUDAGlobalMemoryMb >= 32000)
+DockerUseHOME  = true
+WantGPUHomeMounted = true

transfer_output_files = models/
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT

# Logs: still relative to the container's current working directory
output          = logs/$(ClusterId).$(ProcId).out
error           = logs/$(ClusterId).$(ProcId).err
log             = logs/$(ClusterId).log

queue 1